
export const metadata = {
  icons:{
    icon: "/xaviquesm.png"
  },
  title: "Create Next App",
  description: "Generated by create next app",
};
import Menu from "@/components/admin/menu/page"
export default function RootLayout({ children }) {
  return (
   <>
   <div className="flex bg-[#0A0A0A] ">
         <Menu/>
        {children}
   </div>
   </>
  );
}
