import "./globals.css";
import Navbar from "@/components/main/navbar/navbar";
import Provider from "@/components/provider";
export const metadata = {
  icons:{
    icon: "/xaviquesm.png"
  },
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Provider>
        <Navbar />
        {children}
        </Provider>
      </body>
    </html>
  );
}
